name: Keep 4 releases

on:
  schedule:
    #- cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  clean-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete older releases, keep latest 4
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 4
          keep-old-minor-releases: false   # 不保留旧次要版本，只按数量保留最新 4 个
          dry-run: true                     # 先开启测试模式，确认无误后改为 false